#!/usr/bin/env python
"""Generate a 10-page SYNTHETIC commercial-lines submission PDF for end-to-end testing.

Everything in it is invented. The carriers, agency, applicant, addresses, VINs,
FEIN and policy numbers are fictional and chosen so they cannot collide with a
real entity. It exists so a full generation run can be exercised against known
inputs and the result checked field by field.

Why it is built this way:
  * **Single column, plain text lines.** A two-column layout is exactly what the
    documented pdfplumber label/value scrambling bug feeds on. A controlled cost
    and accuracy test should not also be testing the column-reflow recovery path.
  * **Real text, not a scan.** pdfplumber extracts it directly, so OCR is
    deterministic and the character count is stable run to run.
  * **Explicit Yes/No answers** for a set of underwriting questions, plus topics
    left deliberately unmentioned, so the evidence gate can be graded: correct Y,
    correct N, and correctly BLANK for anything the document never addresses.

Usage:  py scripts/make_test_submission_pdf.py [output.pdf]
"""
from __future__ import annotations

import sys
from pathlib import Path

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

_LEFT = 54
_TOP = 738
_LEADING = 13.2
_FONT = "Helvetica"
_BOLD = "Helvetica-Bold"

PAGES: list[tuple[str, list[str]]] = [
    ("SUBMISSION SUMMARY - APPLICANT AND PRODUCER", [
        "COMMERCIAL LINES SUBMISSION PACKAGE",
        "Submission Date: 03/12/2026",
        "",
        "PRODUCER / AGENCY INFORMATION",
        "Agency Name: Kestrel Commercial Insurance Services",
        "Agency Contact: Dana Whitfield, Commercial Lines Producer",
        "Agency Address: 1180 Larimer Street, Suite 640, Denver, CO 80204",
        "Agency Phone: (303) 555-0148",
        "Agency Fax: (303) 555-0149",
        "Agency Email: dwhitfield@kestrelcommercial.example",
        "Agency Customer ID: KCI-88417",
        "Producer License Number: CO-PC-449120",
        "",
        "APPLICANT INFORMATION",
        "Named Insured: Ridgeline Roofing & Sheet Metal LLC",
        "Doing Business As: Ridgeline Roofing",
        "Legal Entity Type: Limited Liability Company",
        "Mailing Address: 4820 Prospect Avenue, Suite 210, Denver, CO 80216",
        "Physical Address: 4820 Prospect Avenue, Suite 210, Denver, CO 80216",
        "Business Phone: (303) 555-0212",
        "Business Website: www.ridgelineroofing.example",
        "Federal Employer ID Number (FEIN): 84-2210987",
        "State of Incorporation: Colorado",
        "Date Business Started: 04/15/2014",
        "Years in Business: 12",
        "SIC Code: 1761",
        "NAICS Code: 238160",
        "Number of Full Time Employees: 34",
        "Number of Part Time Employees: 6",
        "",
        "CONTACT FOR INSPECTION",
        "Inspection Contact Name: Marcus Ellery, Operations Manager",
        "Inspection Contact Phone: (303) 555-0233",
        "Inspection Contact Email: mellery@ridgelineroofing.example",
        "",
        "ACCOUNTING CONTACT",
        "Accounting Contact Name: Priya Raman, Controller",
        "Accounting Contact Phone: (303) 555-0241",
    ]),
    ("BUSINESS OPERATIONS AND DESCRIPTION", [
        "DESCRIPTION OF OPERATIONS",
        "The applicant is a licensed roofing contractor performing residential and",
        "light commercial roof replacement, roof repair, gutter installation and",
        "sheet metal flashing fabrication. Approximately 70 percent of annual",
        "receipts derive from residential re-roofing and 30 percent from light",
        "commercial flat roof work on single story structures.",
        "",
        "No work is performed at heights above three stories. The applicant does not",
        "perform any structural engineering, does not install solar panels, and does",
        "not perform any hot tar or kettle work. All torch-down application was",
        "discontinued in 2019 and is no longer performed under any circumstances.",
        "",
        "The applicant fabricates custom sheet metal flashing at its Denver shop for",
        "use on its own jobs. Fabricated product is not sold to third parties and is",
        "never shipped outside Colorado.",
        "",
        "SUBCONTRACTOR INFORMATION",
        "Subcontractors are used for approximately 25 percent of labor on commercial",
        "projects only. Every subcontractor is required to provide a certificate of",
        "insurance naming Ridgeline Roofing & Sheet Metal LLC as additional insured",
        "before any work begins. No subcontractor is permitted on a job site without",
        "a current certificate on file. Written contracts with hold harmless",
        "agreements in favor of the applicant are used on all subcontracted work.",
        "Total subcontractor cost for the prior 12 months: $412,000",
        "",
        "FINANCIAL INFORMATION",
        "Annual Gross Sales / Receipts: $4,850,000",
        "Annual Payroll (all employees): $1,640,000",
        "Estimated Annual Gross Sales Next 12 Months: $5,200,000",
        "",
        "QUALITY AND SAFETY",
        "The applicant has a written safety program in operation, reviewed annually.",
        "Monthly documented toolbox safety meetings are held for all field crews.",
        "A written fall protection plan is in force and all field employees receive",
        "OSHA 10 training within 60 days of hire.",
    ]),
    ("POLICY INFORMATION AND PRIOR CARRIER HISTORY", [
        "PROPOSED POLICY INFORMATION",
        "Proposed Effective Date: 05/01/2026",
        "Proposed Expiration Date: 05/01/2027",
        "Billing Plan: Agency Bill",
        "Payment Plan: Quarterly",
        "Audit Frequency: Annual",
        "",
        "CURRENT / EXPIRING POLICY",
        "Carrier Name: Meridian Mutual Casualty Company",
        "NAIC Code: 27341",
        "Policy Number: CPP-4471902-03",
        "Policy Effective Date: 05/01/2025",
        "Policy Expiration Date: 05/01/2026",
        "Total Expiring Annual Premium: $86,400",
        "",
        "LINES OF BUSINESS REQUESTED",
        "Commercial General Liability: Yes",
        "Commercial Property: Yes",
        "Business Auto: Yes",
        "Umbrella / Excess Liability: No",
        "Workers Compensation: Not requested with this submission",
        "Cyber Liability: Not requested with this submission",
        "",
        "PRIOR CARRIER HISTORY - THREE YEARS",
        "2025-2026 Carrier: Meridian Mutual Casualty Company  Premium: $86,400",
        "2024-2025 Carrier: Meridian Mutual Casualty Company  Premium: $81,150",
        "2023-2024 Carrier: Cascade Underwriters Insurance Co  Premium: $77,900",
        "",
        "POLICY HISTORY DISCLOSURES",
        "Has any policy or coverage been declined, cancelled or non-renewed during",
        "the last three years? No. Coverage has been continuously in force since",
        "2014 with no lapse, no cancellation and no non-renewal by any carrier.",
        "",
        "Has the applicant had any judgments or liens during the last five years?",
        "No judgments or liens have been entered against the applicant.",
        "",
        "Is the applicant currently in bankruptcy or receivership? No. The applicant",
        "has never filed for bankruptcy or been placed in receivership.",
    ]),
    ("COMMERCIAL GENERAL LIABILITY - COVERAGE REQUESTED", [
        "GENERAL LIABILITY LIMITS REQUESTED",
        "Each Occurrence Limit: $1,000,000",
        "General Aggregate Limit: $2,000,000",
        "Products / Completed Operations Aggregate Limit: $2,000,000",
        "Personal and Advertising Injury Limit: $1,000,000",
        "Damage to Premises Rented to You: $100,000",
        "Medical Expense Limit (any one person): $10,000",
        "Deductible: $2,500 per occurrence, property damage",
        "",
        "COVERAGE FORM AND BASIS",
        "Coverage Form: Occurrence",
        "General Aggregate Applies Per: Project",
        "Employee Benefits Liability: Not requested",
        "",
        "PREMIUM BASIS AND CLASSIFICATION",
        "Classification: Roofing - residential and light commercial",
        "Class Code: 91560",
        "Premium Basis: Gross Sales",
        "Exposure Amount: $4,850,000",
        "Territory: 002",
        "",
        "Classification: Sheet Metal Work - shop only",
        "Class Code: 92478",
        "Premium Basis: Payroll",
        "Exposure Amount: $310,000",
        "Territory: 002",
        "",
        "ADDITIONAL INSURED REQUIREMENTS",
        "General contractors on commercial projects are routinely added as",
        "additional insured on a primary and non-contributory basis with a waiver",
        "of subrogation. Ongoing and completed operations additional insured",
        "endorsements are required by contract on all commercial work.",
        "",
        "CONTRACTUAL LIABILITY",
        "The applicant assumes liability under written contract with general",
        "contractors for its own work. All such agreements are reviewed by counsel.",
    ]),
    ("GENERAL LIABILITY UNDERWRITING QUESTIONS", [
        "The following questions were answered by the applicant on 03/10/2026.",
        "",
        "1. Does the applicant perform any installation, service or repair work at",
        "   customer premises? Yes. All roofing installation and repair work is",
        "   performed at the customer's premises.",
        "",
        "2. Does the applicant do any work involving blasting, explosives or",
        "   demolition charges? No. No blasting, explosive materials or demolition",
        "   charges are used in any operation.",
        "",
        "3. Does the applicant own, operate or lease any watercraft? No. The",
        "   applicant owns no boats, docks, floating structures or watercraft of any",
        "   kind. All operations are land based.",
        "",
        "4. Does the applicant operate any parking facility or lot for others? No.",
        "   No parking facilities are owned, operated, rented or leased to others.",
        "",
        "5. Are any exposures to radioactive or nuclear materials present? No. No",
        "   radioactive or nuclear material is handled, stored or transported.",
        "",
        "6. Do operations involve storing, treating, discharging, applying,",
        "   disposing or transporting hazardous material? Yes. Used roofing sealant,",
        "   spent solvent and scrap asphalt shingle are accumulated in a covered",
        "   bunker at the Denver shop and removed monthly under manifest by Front",
        "   Range Environmental Services, a licensed hazardous waste hauler.",
        "",
        "7. Does the applicant provide any product warranties or guarantees beyond",
        "   an express written warranty? Yes. Ridgeline Roofing provides a ten year",
        "   written workmanship guarantee on all completed re-roofing projects.",
        "",
        "8. Are day care facilities operated or controlled by the applicant? No. The",
        "   applicant operates no day care facility of any kind.",
        "",
        "9. Does the applicant sponsor any athletic teams, social events or",
        "   recreational activities? No such activities are sponsored or organized.",
    ]),
    ("PROPERTY SECTION - LOCATION AND BUILDING DETAIL", [
        "PREMISES INFORMATION",
        "",
        "Location 1 - Building 1",
        "Street Address: 4820 Prospect Avenue, Suite 210, Denver, CO 80216",
        "County: Denver",
        "Occupancy: Contractor office and sheet metal fabrication shop",
        "Interest: Tenant",
        "Building Description: One story masonry non-combustible warehouse/office",
        "Construction Type: Masonry Non-Combustible",
        "Year Built: 1998",
        "Total Building Area: 18,400 square feet",
        "Number of Stories: 1",
        "Area Occupied by Applicant: 12,600 square feet",
        "Roof Type: Modified bitumen, fully replaced 2021",
        "Wiring Year: 1998, updated 2016",
        "Plumbing Year: 1998",
        "Heating Year: 2016",
        "Roof Updated Year: 2021",
        "",
        "COVERAGE REQUESTED - LOCATION 1",
        "Business Personal Property Limit: $685,000",
        "Tenant Improvements and Betterments: $140,000",
        "Business Income with Extra Expense: $450,000",
        "Valuation Basis: Replacement Cost",
        "Coinsurance: 90 percent",
        "Causes of Loss Form: Special",
        "Deductible: $5,000",
        "Inflation Guard: 4 percent",
        "",
        "PROTECTION AND EXPOSURE",
        "Protection Class: 2",
        "Distance to Responding Fire Station: 1.4 miles",
        "Distance to Fire Hydrant: 180 feet",
        "Sprinklered: Yes, 100 percent wet pipe system, inspected 11/2025",
        "Burglar Alarm: Central station, certificate on file",
        "Fire Alarm: Central station, monitored 24 hours",
    ]),
    ("PROPERTY SECTION - ADDITIONAL DETAIL AND EXPOSURES", [
        "Location 2 - Building 1",
        "Street Address: 3110 Vasquez Boulevard, Denver, CO 80216",
        "County: Denver",
        "Occupancy: Fenced equipment and material storage yard",
        "Interest: Tenant",
        "Building Description: Open storage yard, no building",
        "Total Lot Area: 24,000 square feet",
        "Year Fencing Installed: 2019",
        "",
        "COVERAGE REQUESTED - LOCATION 2",
        "Business Personal Property Limit: $95,000",
        "Valuation Basis: Replacement Cost",
        "Causes of Loss Form: Special",
        "Deductible: $5,000",
        "",
        "PROTECTION - LOCATION 2",
        "Protection Class: 2",
        "Perimeter: Eight foot chain link with barbed wire, locked gate",
        "Lighting: Motion activated perimeter lighting",
        "Burglar Alarm: None at this location",
        "",
        "PROPERTY UNDERWRITING QUESTIONS",
        "Is any building unoccupied or vacant? No. Both locations are fully",
        "occupied and in active daily use.",
        "",
        "Is there any exposure to sink hole or mine subsidence? No known sink hole",
        "or mine subsidence exposure exists at either location.",
        "",
        "Is the property located in a flood zone? No. Both locations are in FEMA",
        "flood zone X, outside the 500 year floodplain.",
        "",
        "Has any building had roof, wiring, plumbing or heating updated? Yes. The",
        "Location 1 roof was fully replaced in 2021, wiring was updated in 2016 and",
        "the heating system was replaced in 2016.",
        "",
        "MORTGAGEE / ADDITIONAL INTEREST",
        "Name: Prospect Avenue Holdings LLC (landlord, Location 1)",
        "Address: 900 South Broadway, Suite 15, Denver, CO 80209",
        "Interest: Loss Payee - Tenant Improvements",
    ]),
    ("BUSINESS AUTO SECTION - VEHICLE SCHEDULE", [
        "AUTO COVERAGE REQUESTED",
        "Liability Combined Single Limit: $1,000,000",
        "Uninsured / Underinsured Motorist: $1,000,000",
        "Medical Payments: $5,000",
        "Comprehensive Deductible: $1,000",
        "Collision Deductible: $1,000",
        "Hired Auto Liability: Yes, requested",
        "Non-Owned Auto Liability: Yes, requested",
        "",
        "SCHEDULE OF OWNED VEHICLES",
        "",
        "Vehicle 1",
        "Year: 2022  Make: Ford  Model: F-250 Super Duty  Body: Pickup",
        "VIN: 1FT7W2BT4NEC10473",
        "Cost New: $58,900   Gross Vehicle Weight: 10,000 lbs",
        "Garaging Address: 4820 Prospect Avenue, Denver, CO 80216",
        "Radius of Operation: 50 miles   Use: Service",
        "",
        "Vehicle 2",
        "Year: 2021  Make: Ram  Model: 3500  Body: Flatbed",
        "VIN: 3C63RRHL9MG551208",
        "Cost New: $67,400   Gross Vehicle Weight: 14,000 lbs",
        "Garaging Address: 4820 Prospect Avenue, Denver, CO 80216",
        "Radius of Operation: 50 miles   Use: Service",
        "",
        "Vehicle 3",
        "Year: 2023  Make: Isuzu  Model: NPR-HD  Body: Stake Bed",
        "VIN: 54DC4W1D0PS812640",
        "Cost New: $81,250   Gross Vehicle Weight: 14,500 lbs",
        "Garaging Address: 3110 Vasquez Boulevard, Denver, CO 80216",
        "Radius of Operation: 50 miles   Use: Service",
        "",
        "Vehicle 4",
        "Year: 2020  Make: Chevrolet  Model: Silverado 1500  Body: Pickup",
        "VIN: 1GCRYDED9LZ227719",
        "Cost New: $41,800   Gross Vehicle Weight: 7,000 lbs",
        "Garaging Address: 4820 Prospect Avenue, Denver, CO 80216",
        "Radius of Operation: 50 miles   Use: Service",
    ]),
    ("BUSINESS AUTO SECTION - DRIVERS AND UNDERWRITING", [
        "SCHEDULE OF DRIVERS",
        "",
        "Driver 1: Marcus Ellery   Date of Birth: 07/22/1981",
        "License Number: CO-D4471902   State: CO   Years Experience: 19",
        "Date of Hire: 06/01/2015",
        "",
        "Driver 2: Anthony Braddock   Date of Birth: 11/09/1990",
        "License Number: CO-D5518830   State: CO   Years Experience: 11",
        "Date of Hire: 03/14/2018",
        "",
        "Driver 3: Luis Ferreira   Date of Birth: 02/28/1986",
        "License Number: CO-D6620145   State: CO   Years Experience: 15",
        "Date of Hire: 08/02/2016",
        "",
        "Driver 4: Sandra Oyelaran   Date of Birth: 05/16/1994",
        "License Number: CO-D7734902   State: CO   Years Experience: 7",
        "Date of Hire: 01/09/2021",
        "",
        "AUTO UNDERWRITING QUESTIONS",
        "",
        "Are any vehicles leased or rented to others? No. No vehicle owned by the",
        "applicant is leased, rented or loaned to any other party at any time.",
        "",
        "Is there a vehicle maintenance program in operation? Yes. A written",
        "preventive maintenance schedule is in force. Every unit receives a",
        "documented service inspection every 5,000 miles and records are retained.",
        "",
        "Are motor vehicle records ordered on all drivers? Yes. An MVR is pulled on",
        "every driver at hire and re-ordered annually for all listed drivers.",
        "",
        "Does the applicant transport hazardous materials by vehicle? Yes. Spent",
        "solvent and used sealant are moved from job sites to the Denver bunker in",
        "company vehicles under a Colorado transporter registration.",
        "",
        "Are any drivers under the age of 21? No. All listed drivers are over 25.",
    ]),
    ("LOSS HISTORY, CERTIFICATE HOLDERS AND ATTESTATION", [
        "FIVE YEAR LOSS HISTORY - ALL LINES",
        "",
        "Claim 1",
        "Date of Loss: 08/17/2023   Line of Business: General Liability",
        "Description: Wind driven rain entered a partially completed re-roof at a",
        "residential job site causing interior ceiling and drywall damage.",
        "Amount Paid: $18,400   Reserve: $0   Status: Closed",
        "",
        "Claim 2",
        "Date of Loss: 02/03/2024   Line of Business: Business Auto",
        "Description: Insured vehicle backed into a parked vehicle in a supply yard.",
        "Amount Paid: $6,250   Reserve: $0   Status: Closed",
        "",
        "Claim 3",
        "Date of Loss: 11/29/2025   Line of Business: Commercial Property",
        "Description: Hail damage to stored sheet metal stock at Location 2.",
        "Amount Paid: $12,900   Reserve: $4,000   Status: Open",
        "",
        "Total Incurred, Five Years: $41,550",
        "Number of Claims, Five Years: 3",
        "",
        "CERTIFICATE HOLDER",
        "Name: Alder Creek General Contractors Inc",
        "Address: 275 West Hampden Avenue, Englewood, CO 80110",
        "Relationship: General contractor - additional insured, ongoing and",
        "completed operations, primary and non-contributory, waiver of subrogation.",
        "Certificate Description of Operations: Roofing and sheet metal work",
        "performed by Ridgeline Roofing & Sheet Metal LLC as subcontractor on the",
        "Alder Creek Commons project, 1900 South Federal Boulevard, Denver, CO.",
        "",
        "ATTESTATION",
        "The undersigned declares that the statements above are true and complete to",
        "the best of their knowledge.",
        "Signature of Applicant: Marcus Ellery, Operations Manager",
        "Date Signed: 03/10/2026",
    ]),
]


def build(out_path: Path) -> str:
    """Render the PDF and return the exact text laid down, for char accounting."""
    c = canvas.Canvas(str(out_path), pagesize=LETTER)
    laid_down: list[str] = []

    for page_no, (heading, lines) in enumerate(PAGES, start=1):
        c.setFont(_BOLD, 11.5)
        c.drawString(_LEFT, _TOP + 22, heading)
        c.setFont(_FONT, 9.4)
        y = _TOP
        for line in lines:
            c.drawString(_LEFT, y, line)
            y -= _LEADING
        c.setFont(_FONT, 8)
        c.drawString(_LEFT, 42, f"Ridgeline Roofing & Sheet Metal LLC - Submission Package")
        c.drawRightString(LETTER[0] - _LEFT, 42, f"Page {page_no} of {len(PAGES)}")
        laid_down.append(heading + "\n" + "\n".join(lines))
        c.showPage()

    c.save()
    return "\n\n".join(laid_down)


if __name__ == "__main__":
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "test_submission_ridgeline.pdf")
    text = build(out)
    print(f"Wrote {out.resolve()}")
    print(f"Pages: {len(PAGES)}")
    print(f"Text laid down: {len(text):,} chars, {len(text.split()):,} words")
