export const PLANS = [
  {
    id: "essentials",
    name: "Essentials",
    monthlyPrice: 59,
    annualPrice: 49,
    packageCount: "50 scores/mo",
    overage: "$1.75/score",
    featured: false,
    badge: null,
    cta: "Upgrade",
    features: [
      "50 scores / month",
      "Submission Quality Scoring (SQS)",
      "Cross-form validation",
      "Client-in-the-Loop™ remediation",
      "Coversheet & submittable narrative",
      "Unlimited users",
    ],
    missing: [],
  },
  {
    id: "professional",
    name: "Professional",
    monthlyPrice: 129,
    annualPrice: 99,
    packageCount: "100 packages/mo",
    overage: "$1.50/package",
    featured: false,
    badge: null,
    cta: "Upgrade",
    features: [
      "100 packages / month",
      "All Essentials features",
      "800+ ACORD forms",
      "Guided form completion",
      "E&O defense",
      "Email support",
    ],
    missing: [],
  },
  {
    id: "business",
    name: "Business",
    monthlyPrice: 449,
    annualPrice: 399,
    packageCount: "400 packages/mo",
    overage: "$1.25/package",
    featured: true,
    badge: "Most popular",
    cta: "Upgrade",
    features: [
      "400 packages / month",
      "All Professional features",
      "Supplemental forms",
      "Advanced client questionnaires",
      "Renewal workspace",
      "Priority support",
    ],
    missing: [],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthlyPrice: null,
    annualPrice: null,
    packageCount: "Custom packages/mo",
    overage: "Custom",
    featured: false,
    badge: null,
    cta: "Contact sales",
    features: [
      "All Business features",
      "Custom integrations",
      "Unlimited users",
      "Team analytics & reporting",
      "On-prem deployment",
      "Dedicated account manager",
    ],
    missing: [],
  },
];
